name: Telegram
on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          😍 A YIP pull request has been merged on GitHub!
          ${{ github.actor }}: ${{ github.event.head_commit.message }}
